<?php
/**
 * DataTablesApi
 * PHP version 5
 *
 * @category Class
 * @package  Catalytic\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Catalytic SDK API
 *
 * ## API for the Catalytic SDK
 *
 * OpenAPI spec version: v1.0.0
 * Contact: developers@catalytic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Catalytic\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Catalytic\Client\ApiException;
use Catalytic\Client\Configuration;
use Catalytic\Client\HeaderSelector;
use Catalytic\Client\ObjectSerializer;

/**
 * DataTablesApi Class Doc Comment
 *
 * @category Class
 * @package  Catalytic\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DataTablesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation downloadDataTable
     *
     * Download a Data Table as a CSV or Excel file
     *
     * @param  string $id The ID of the Data Table to download (required)
     * @param  \Catalytic\Client\Model\DataTableExportFormat $format The format to export the data table in. csv (default) or excel (optional)
     *
     * @throws \Catalytic\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string
     */
    public function downloadDataTable($id, $format = null)
    {
        list($response) = $this->downloadDataTableWithHttpInfo($id, $format);
        return $response;
    }

    /**
     * Operation downloadDataTableWithHttpInfo
     *
     * Download a Data Table as a CSV or Excel file
     *
     * @param  string $id The ID of the Data Table to download (required)
     * @param  \Catalytic\Client\Model\DataTableExportFormat $format The format to export the data table in. csv (default) or excel (optional)
     *
     * @throws \Catalytic\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function downloadDataTableWithHttpInfo($id, $format = null)
    {
        $returnType = 'string';
        $request = $this->downloadDataTableRequest($id, $format);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Catalytic\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Catalytic\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation downloadDataTableAsync
     *
     * Download a Data Table as a CSV or Excel file
     *
     * @param  string $id The ID of the Data Table to download (required)
     * @param  \Catalytic\Client\Model\DataTableExportFormat $format The format to export the data table in. csv (default) or excel (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function downloadDataTableAsync($id, $format = null)
    {
        return $this->downloadDataTableAsyncWithHttpInfo($id, $format)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation downloadDataTableAsyncWithHttpInfo
     *
     * Download a Data Table as a CSV or Excel file
     *
     * @param  string $id The ID of the Data Table to download (required)
     * @param  \Catalytic\Client\Model\DataTableExportFormat $format The format to export the data table in. csv (default) or excel (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function downloadDataTableAsyncWithHttpInfo($id, $format = null)
    {
        $returnType = 'string';
        $request = $this->downloadDataTableRequest($id, $format);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'downloadDataTable'
     *
     * @param  string $id The ID of the Data Table to download (required)
     * @param  \Catalytic\Client\Model\DataTableExportFormat $format The format to export the data table in. csv (default) or excel (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function downloadDataTableRequest($id, $format = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling downloadDataTable'
            );
        }

        $resourcePath = '/api/tables/{id}:download';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($format !== null) {
            $queryParams['format'] = ObjectSerializer::toQueryValue($format);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'application/octet-stream']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'application/octet-stream'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation findDataTables
     *
     * Find Data Tables
     *
     * @param  string $query Free text query terms to search all attributes for (optional)
     * @param  string $status Run or task status to search for (optional)
     * @param  string $process_id Process ID (aka Pushbot ID) to search for (optional)
     * @param  string $run_id RunID (aka Instance ID) to search for (optional)
     * @param  string $owner Run or task owner to search for (optional)
     * @param  string $category Category of process or run to search for (optional)
     * @param  string $page_token The token representing the result page to get (optional)
     * @param  int $page_size The page size requested (optional)
     *
     * @throws \Catalytic\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Catalytic\Client\Model\DataTablesPage
     */
    public function findDataTables($query = null, $status = null, $process_id = null, $run_id = null, $owner = null, $category = null, $page_token = null, $page_size = null)
    {
        list($response) = $this->findDataTablesWithHttpInfo($query, $status, $process_id, $run_id, $owner, $category, $page_token, $page_size);
        return $response;
    }

    /**
     * Operation findDataTablesWithHttpInfo
     *
     * Find Data Tables
     *
     * @param  string $query Free text query terms to search all attributes for (optional)
     * @param  string $status Run or task status to search for (optional)
     * @param  string $process_id Process ID (aka Pushbot ID) to search for (optional)
     * @param  string $run_id RunID (aka Instance ID) to search for (optional)
     * @param  string $owner Run or task owner to search for (optional)
     * @param  string $category Category of process or run to search for (optional)
     * @param  string $page_token The token representing the result page to get (optional)
     * @param  int $page_size The page size requested (optional)
     *
     * @throws \Catalytic\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Catalytic\Client\Model\DataTablesPage, HTTP status code, HTTP response headers (array of strings)
     */
    public function findDataTablesWithHttpInfo($query = null, $status = null, $process_id = null, $run_id = null, $owner = null, $category = null, $page_token = null, $page_size = null)
    {
        $returnType = '\Catalytic\Client\Model\DataTablesPage';
        $request = $this->findDataTablesRequest($query, $status, $process_id, $run_id, $owner, $category, $page_token, $page_size);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Catalytic\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Catalytic\Client\Model\DataTablesPage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findDataTablesAsync
     *
     * Find Data Tables
     *
     * @param  string $query Free text query terms to search all attributes for (optional)
     * @param  string $status Run or task status to search for (optional)
     * @param  string $process_id Process ID (aka Pushbot ID) to search for (optional)
     * @param  string $run_id RunID (aka Instance ID) to search for (optional)
     * @param  string $owner Run or task owner to search for (optional)
     * @param  string $category Category of process or run to search for (optional)
     * @param  string $page_token The token representing the result page to get (optional)
     * @param  int $page_size The page size requested (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findDataTablesAsync($query = null, $status = null, $process_id = null, $run_id = null, $owner = null, $category = null, $page_token = null, $page_size = null)
    {
        return $this->findDataTablesAsyncWithHttpInfo($query, $status, $process_id, $run_id, $owner, $category, $page_token, $page_size)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findDataTablesAsyncWithHttpInfo
     *
     * Find Data Tables
     *
     * @param  string $query Free text query terms to search all attributes for (optional)
     * @param  string $status Run or task status to search for (optional)
     * @param  string $process_id Process ID (aka Pushbot ID) to search for (optional)
     * @param  string $run_id RunID (aka Instance ID) to search for (optional)
     * @param  string $owner Run or task owner to search for (optional)
     * @param  string $category Category of process or run to search for (optional)
     * @param  string $page_token The token representing the result page to get (optional)
     * @param  int $page_size The page size requested (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findDataTablesAsyncWithHttpInfo($query = null, $status = null, $process_id = null, $run_id = null, $owner = null, $category = null, $page_token = null, $page_size = null)
    {
        $returnType = '\Catalytic\Client\Model\DataTablesPage';
        $request = $this->findDataTablesRequest($query, $status, $process_id, $run_id, $owner, $category, $page_token, $page_size);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findDataTables'
     *
     * @param  string $query Free text query terms to search all attributes for (optional)
     * @param  string $status Run or task status to search for (optional)
     * @param  string $process_id Process ID (aka Pushbot ID) to search for (optional)
     * @param  string $run_id RunID (aka Instance ID) to search for (optional)
     * @param  string $owner Run or task owner to search for (optional)
     * @param  string $category Category of process or run to search for (optional)
     * @param  string $page_token The token representing the result page to get (optional)
     * @param  int $page_size The page size requested (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function findDataTablesRequest($query = null, $status = null, $process_id = null, $run_id = null, $owner = null, $category = null, $page_token = null, $page_size = null)
    {

        $resourcePath = '/api/tables';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($query !== null) {
            $queryParams['query'] = ObjectSerializer::toQueryValue($query);
        }
        // query params
        if ($status !== null) {
            $queryParams['status'] = ObjectSerializer::toQueryValue($status);
        }
        // query params
        if ($process_id !== null) {
            $queryParams['process_id'] = ObjectSerializer::toQueryValue($process_id);
        }
        // query params
        if ($run_id !== null) {
            $queryParams['run_id'] = ObjectSerializer::toQueryValue($run_id);
        }
        // query params
        if ($owner !== null) {
            $queryParams['owner'] = ObjectSerializer::toQueryValue($owner);
        }
        // query params
        if ($category !== null) {
            $queryParams['category'] = ObjectSerializer::toQueryValue($category);
        }
        // query params
        if ($page_token !== null) {
            $queryParams['page_token'] = ObjectSerializer::toQueryValue($page_token);
        }
        // query params
        if ($page_size !== null) {
            $queryParams['page_size'] = ObjectSerializer::toQueryValue($page_size);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDataTable
     *
     * Get metadata for a Data Table by ID
     *
     * @param  string $id The ID of the Data Table to get metadata for (required)
     *
     * @throws \Catalytic\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Catalytic\Client\Model\DataTable
     */
    public function getDataTable($id)
    {
        list($response) = $this->getDataTableWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation getDataTableWithHttpInfo
     *
     * Get metadata for a Data Table by ID
     *
     * @param  string $id The ID of the Data Table to get metadata for (required)
     *
     * @throws \Catalytic\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Catalytic\Client\Model\DataTable, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDataTableWithHttpInfo($id)
    {
        $returnType = '\Catalytic\Client\Model\DataTable';
        $request = $this->getDataTableRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Catalytic\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Catalytic\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Catalytic\Client\Model\DataTable',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getDataTableAsync
     *
     * Get metadata for a Data Table by ID
     *
     * @param  string $id The ID of the Data Table to get metadata for (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDataTableAsync($id)
    {
        return $this->getDataTableAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDataTableAsyncWithHttpInfo
     *
     * Get metadata for a Data Table by ID
     *
     * @param  string $id The ID of the Data Table to get metadata for (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDataTableAsyncWithHttpInfo($id)
    {
        $returnType = '\Catalytic\Client\Model\DataTable';
        $request = $this->getDataTableRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDataTable'
     *
     * @param  string $id The ID of the Data Table to get metadata for (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getDataTableRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getDataTable'
            );
        }

        $resourcePath = '/api/tables/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation uploadDataTable
     *
     * Upload a csv or excel file to create a data table
     *
     * @param  string[] $files files (optional)
     * @param  string $table_name The name of the table to create. Defaults to the file name without the extension (optional)
     * @param  int $header_row The row number that contains the column headers. Defaults to 1. (optional)
     * @param  int $sheet_number The number of the sheet to import. Only applies to Excel files. The first sheet is imported by default. (optional)
     *
     * @throws \Catalytic\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Catalytic\Client\Model\DataTable
     */
    public function uploadDataTable($files = null, $table_name = null, $header_row = null, $sheet_number = null)
    {
        list($response) = $this->uploadDataTableWithHttpInfo($files, $table_name, $header_row, $sheet_number);
        return $response;
    }

    /**
     * Operation uploadDataTableWithHttpInfo
     *
     * Upload a csv or excel file to create a data table
     *
     * @param  string[] $files (optional)
     * @param  string $table_name The name of the table to create. Defaults to the file name without the extension (optional)
     * @param  int $header_row The row number that contains the column headers. Defaults to 1. (optional)
     * @param  int $sheet_number The number of the sheet to import. Only applies to Excel files. The first sheet is imported by default. (optional)
     *
     * @throws \Catalytic\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Catalytic\Client\Model\DataTable, HTTP status code, HTTP response headers (array of strings)
     */
    public function uploadDataTableWithHttpInfo($files = null, $table_name = null, $header_row = null, $sheet_number = null)
    {
        $returnType = '\Catalytic\Client\Model\DataTable';
        $request = $this->uploadDataTableRequest($files, $table_name, $header_row, $sheet_number);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Catalytic\Client\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Catalytic\Client\Model\DataTable',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation uploadDataTableAsync
     *
     * Upload a csv or excel file to create a data table
     *
     * @param  string[] $files (optional)
     * @param  string $table_name The name of the table to create. Defaults to the file name without the extension (optional)
     * @param  int $header_row The row number that contains the column headers. Defaults to 1. (optional)
     * @param  int $sheet_number The number of the sheet to import. Only applies to Excel files. The first sheet is imported by default. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadDataTableAsync($files = null, $table_name = null, $header_row = null, $sheet_number = null)
    {
        return $this->uploadDataTableAsyncWithHttpInfo($files, $table_name, $header_row, $sheet_number)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation uploadDataTableAsyncWithHttpInfo
     *
     * Upload a csv or excel file to create a data table
     *
     * @param  string[] $files (optional)
     * @param  string $table_name The name of the table to create. Defaults to the file name without the extension (optional)
     * @param  int $header_row The row number that contains the column headers. Defaults to 1. (optional)
     * @param  int $sheet_number The number of the sheet to import. Only applies to Excel files. The first sheet is imported by default. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadDataTableAsyncWithHttpInfo($files = null, $table_name = null, $header_row = null, $sheet_number = null)
    {
        $returnType = '\Catalytic\Client\Model\DataTable';
        $request = $this->uploadDataTableRequest($files, $table_name, $header_row, $sheet_number);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'uploadDataTable'
     *
     * @param  string[] $files (optional)
     * @param  string $table_name The name of the table to create. Defaults to the file name without the extension (optional)
     * @param  int $header_row The row number that contains the column headers. Defaults to 1. (optional)
     * @param  int $sheet_number The number of the sheet to import. Only applies to Excel files. The first sheet is imported by default. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function uploadDataTableRequest($files = null, $table_name = null, $header_row = null, $sheet_number = null)
    {

        $resourcePath = '/api/tables/:upload';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($table_name !== null) {
            $queryParams['tableName'] = ObjectSerializer::toQueryValue($table_name);
        }
        // query params
        if ($header_row !== null) {
            $queryParams['headerRow'] = ObjectSerializer::toQueryValue($header_row);
        }
        // query params
        if ($sheet_number !== null) {
            $queryParams['sheetNumber'] = ObjectSerializer::toQueryValue($sheet_number);
        }


        // form params
        if ($files !== null) {
            $formParams['files'] = ObjectSerializer::toFormValue($files);
        }
        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
