#!/bin/bash

# Regenerate from the openapi spec and dump to dir /new
openapi-generator generate -i https://catalyticsdkapi-31.azurewebsites.net/swagger/v1/swagger.json \
    -g php \
    -o new \
    --additional-properties=invokerPackage=Catalytic\\SDK,variableNamingConvention=camelCase \
    --skip-validate-spec;

rm -fr ./lib/generated;

# Move the files we need from /new to /lib/generated
mv ./new/lib/ ./lib/generated;

# Delete /new dir
rm -fr ./new;