<?php
/**
 * PushbotTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Catalytic\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Catalytic SDK API
 *
 * ## API for the Catalytic SDK
 *
 * OpenAPI spec version: v1.0.0
 * Contact: developers@catalytic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Catalytic\Client;

/**
 * PushbotTest Class Doc Comment
 *
 * @category    Class
 * @description Pushbot
 * @package     Catalytic\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PushbotTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Pushbot"
     */
    public function testPushbot()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "team_name"
     */
    public function testPropertyTeamName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "input_fields"
     */
    public function testPropertyInputFields()
    {
    }

    /**
     * Test attribute "is_published"
     */
    public function testPropertyIsPublished()
    {
    }

    /**
     * Test attribute "is_archived"
     */
    public function testPropertyIsArchived()
    {
    }

    /**
     * Test attribute "field_visibility"
     */
    public function testPropertyFieldVisibility()
    {
    }

    /**
     * Test attribute "instance_visibility"
     */
    public function testPropertyInstanceVisibility()
    {
    }

    /**
     * Test attribute "admin_users"
     */
    public function testPropertyAdminUsers()
    {
    }

    /**
     * Test attribute "standard_users"
     */
    public function testPropertyStandardUsers()
    {
    }

    /**
     * Test attribute "read_only_users"
     */
    public function testPropertyReadOnlyUsers()
    {
    }

    /**
     * Test attribute "task_count_limit"
     */
    public function testPropertyTaskCountLimit()
    {
    }

    /**
     * Test attribute "field_count_limit"
     */
    public function testPropertyFieldCountLimit()
    {
    }

    /**
     * Test attribute "field_size_limit"
     */
    public function testPropertyFieldSizeLimit()
    {
    }

    /**
     * Test attribute "field_total_size_limit"
     */
    public function testPropertyFieldTotalSizeLimit()
    {
    }

    /**
     * Test attribute "data_table_row_limit"
     */
    public function testPropertyDataTableRowLimit()
    {
    }

    /**
     * Test attribute "data_table_column_limit"
     */
    public function testPropertyDataTableColumnLimit()
    {
    }

    /**
     * Test attribute "data_table_cell_limit"
     */
    public function testPropertyDataTableCellLimit()
    {
    }
}
