<?php
/**
 * DataTablesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Catalytic\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Catalytic SDK API
 *
 * ## API for the Catalytic SDK
 *
 * OpenAPI spec version: v1.0.0
 * Contact: developers@catalytic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Catalytic\Client;

use Catalytic\Client\Configuration;
use Catalytic\Client\ApiException;
use Catalytic\Client\ObjectSerializer;

/**
 * DataTablesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Catalytic\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DataTablesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for downloadDataTable
     *
     * Download a Data Table as a CSV or Excel file.
     *
     */
    public function testDownloadDataTable()
    {
    }

    /**
     * Test case for findDataTables
     *
     * Find Data Tables.
     *
     */
    public function testFindDataTables()
    {
    }

    /**
     * Test case for getDataTable
     *
     * Get metadata for a Data Table by ID.
     *
     */
    public function testGetDataTable()
    {
    }

    /**
     * Test case for uploadDataTable
     *
     * Upload a csv or excel file to create a data table.
     *
     */
    public function testUploadDataTable()
    {
    }
}
